

# This file was generated by /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/tools/img2py.py

from wx.lib.embeddedimage import PyEmbeddedImage

fegan_ico = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABHNCSVQICAgIfAhkiAAAAWpJ"
    "REFUaIHdmk0SwjAIhV8dt81hvYB6gR62PUDddfxpEiAQiG/ljGaSTwoPohPw2DGwrgCA/U5e"
    "sG6b1VnYSmnBhb1oni3OIhYbAIgFIQIA4kBcWxaneTbPiZSW4/W63n7eF0fg2MAwEu+Hzykf"
    "gelJ34j8SX01R8BbfwzAMDdP/UcEsqVwgCgcVWjdNl5JJMK1+ASljH48Qham1OITZ8b1rR8f"
    "YEeCoBbHrkGcJnG0SJSUrUKjQBTL6AgQLj6gCeFmZFoQrk6sAdE00GioNrDU5NsLMWaOnOQR"
    "UNhcQ6G6UUlOhAIA+BDhAAAeREgAgA4hTuKzksd+hiuFgNLFqkaA3TsRhqLal6JuZBaTXSkS"
    "JjnQs4s1S+JeEKZVqAeEeRm1hujiA5YQ3YzM6neErk5sAdG9ldCGcOmFNCHcmjktCNduVAOi"
    "CFC6HabcHFPUCpEFoBwwAkSYgUYKkW2nJXc0rZJc7U+j/93mBa+2fHkzLCHRAAAAAElFTkSu"
    "QmCC")
getData = fegan_ico.GetData
getImage = fegan_ico.GetImage
getBitmap = fegan_ico.GetBitmap
getIcon = fegan_ico.GetIcon
